# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import game_pb2 as game__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in game_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GameServiceStub(object):
    """서비스 정의 (서버에서 제공하는 기능)
    Define the service (functions provided by the server)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPlayerState = channel.unary_unary(
                '/GameService/GetPlayerState',
                request_serializer=game__pb2.PlayerRequest.SerializeToString,
                response_deserializer=game__pb2.PlayerResponse.FromString,
                _registered_method=True)


class GameServiceServicer(object):
    """서비스 정의 (서버에서 제공하는 기능)
    Define the service (functions provided by the server)
    """

    def GetPlayerState(self, request, context):
        """GetPlayerState 메서드 정의 (요청을 보내면 응답을 반환함)
        GetPlayerState method: Receives a request and returns a response
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GameServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPlayerState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlayerState,
                    request_deserializer=game__pb2.PlayerRequest.FromString,
                    response_serializer=game__pb2.PlayerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GameService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('GameService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GameService(object):
    """서비스 정의 (서버에서 제공하는 기능)
    Define the service (functions provided by the server)
    """

    @staticmethod
    def GetPlayerState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/GameService/GetPlayerState',
            game__pb2.PlayerRequest.SerializeToString,
            game__pb2.PlayerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
